const doo = "C4";
const ree = "D4";
const mi = "E4";
const fa = "F4";
const sol = "G4";
const la = "A4";
const si = "B4";

export const musics = {
  BRILHA_ESTRELINHA: [
    doo,
    doo,
    sol,
    sol,
    la,
    la,
    sol,
    sol,
    fa,
    fa,
    mi,
    mi,
    ree,
    ree,
    ree,
    ree,
    doo,
    sol,
    sol,
    fa,
    fa,
    mi,
    mi,
    ree,
    ree,
    ree,
    ree,
    sol,
    sol,
    fa,
    fa,
    mi,
    mi,
    ree,
    ree,
    ree,
    ree,
    doo,
    doo,
    sol,
    sol,
    la,
    la,
    sol,
    sol,
    fa,
    fa,
    mi,
    mi,
    ree,
    ree,
    ree,
    ree,
    doo,
  ],

  ODE_A_ALEGRIA: [
    { note: mi, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: fa, tempo: 0.5 },
    { note: sol, tempo: 0.5 },
    { note: sol, tempo: 0.5 },
    { note: fa, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: doo, tempo: 0.5 },
    { note: doo, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: mi, tempo: 2 },
    { note: ree, tempo: 0.5 },
    { note: ree, tempo: 3 },
    { note: mi, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: fa, tempo: 0.5 },
    { note: sol, tempo: 0.5 },
    { note: sol, tempo: 0.5 },
    { note: fa, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: doo, tempo: 0.5 },
    { note: doo, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: doo, tempo: 0.5 },
    { note: doo, tempo: 3 },
    { note: ree, tempo: 0.5 },
    { note: doo, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: doo, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: fa, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: doo, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: fa, tempo: 0.5 },
    { note: mi, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: doo, tempo: 0.5 },
    { note: ree, tempo: 0.5 },
    { note: sol, tempo: 4 },
  ],
};
